var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/course/[id]/chat/page.js")
R.c("server/chunks/ssr/_c7888d7c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__d0935222._.js")
R.c("server/chunks/ssr/_82724d14._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5ed11e61._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e17d8479._.js")
R.c("server/chunks/ssr/[root-of-the-server]__666f8ec1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__4c1e03ea._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_course_[id]_chat_page_actions_dba84fda.js")
R.m(79361)
module.exports=R.m(79361).exports
