var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/course/[id]/page.js")
R.c("server/chunks/ssr/_46c4ff58._.js")
R.c("server/chunks/ssr/[root-of-the-server]__d0935222._.js")
R.c("server/chunks/ssr/_14c2d093._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5ed11e61._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e17d8479._.js")
R.c("server/chunks/ssr/[root-of-the-server]__666f8ec1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__4c1e03ea._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_course_[id]_page_actions_e3c23ea3.js")
R.m(19264)
module.exports=R.m(19264).exports
