var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/account/page.js")
R.c("server/chunks/ssr/_f9068b25._.js")
R.c("server/chunks/ssr/[root-of-the-server]__d0935222._.js")
R.c("server/chunks/ssr/_da612e33._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5ed11e61._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e17d8479._.js")
R.c("server/chunks/ssr/[root-of-the-server]__666f8ec1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__4c1e03ea._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_account_page_actions_0a55de6a.js")
R.m(33371)
module.exports=R.m(33371).exports
